# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_auto_20151108_2019'),
        ('groupmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPartial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.BooleanField(default=False)),
                ('laboratory', models.BooleanField(default=False)),
                ('project', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
                ('exhibition', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.FloatField(default=0.0, null=True)),
                ('laboratory', models.FloatField(default=0.0, null=True)),
                ('project', models.FloatField(default=0.0, null=True)),
                ('review', models.FloatField(default=0.0, null=True)),
                ('exhibition', models.FloatField(default=0.0, null=True)),
                ('configuration_partial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groupmodule.ConfigurationPartial')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupmodule.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Partial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('configuration_partial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groupmodule.ConfigurationPartial')),
                ('evaluation_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groupmodule.EvaluationType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupmodule.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('career', models.CharField(max_length=80, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupmodule.Period')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField(default=False)),
                ('participation', models.FloatField(default=0.0, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupmodule.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Student')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupmodule.Signature'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(through='groupmodule.StudentGroup', to='usermodule.Student'),
        ),
    ]
