# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupmodule', '0002_auto_20160105_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
