# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupmodule', '0003_auto_20160114_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='code',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
